package captive

import (
	"net/netip"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderDNSMasqConfig(t *testing.T) {
	got, err := renderDNSMasqConfig(netip.MustParseAddr("10.42.0.1"))
	if err != nil {
		t.Fatalf("renderDNSMasqConfig() error = %v", err)
	}
	want := "# Generated by onboardd. Do not edit.\n" +
		"address=/#/10.42.0.1\n" +
		"local=/#/\n" +
		"local-ttl=0\n"
	if got != want {
		t.Fatalf("renderDNSMasqConfig() = %q, want %q", got, want)
	}
}

func TestRenderDNSMasqConfigRejectsUnusableAddresses(t *testing.T) {
	for _, address := range []netip.Addr{
		{},
		netip.IPv6Unspecified(),
		netip.IPv4Unspecified(),
		netip.MustParseAddr("224.0.0.1"),
	} {
		t.Run(address.String(), func(t *testing.T) {
			if _, err := renderDNSMasqConfig(address); err == nil {
				t.Fatalf("renderDNSMasqConfig(%s) unexpectedly succeeded", address)
			}
		})
	}
}

func TestNewDNSConfigFileValidatesPath(t *testing.T) {
	for _, path := range []string{"", "onboardd.conf", "."} {
		t.Run(path, func(t *testing.T) {
			if _, err := NewDNSConfigFile(path); err == nil {
				t.Fatalf("NewDNSConfigFile(%q) unexpectedly succeeded", path)
			}
		})
	}
}

func TestDNSConfigFileInstallReplaceAndRemove(t *testing.T) {
	path := filepath.Join(t.TempDir(), "NetworkManager", "dnsmasq-shared.d", "onboardd.conf")
	config, err := NewDNSConfigFile(path)
	if err != nil {
		t.Fatal(err)
	}

	if err := config.Install(netip.MustParseAddr("10.42.0.1")); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	assertDNSConfigFile(t, path, "address=/#/10.42.0.1")

	if err := config.Install(netip.MustParseAddr("192.168.50.1")); err != nil {
		t.Fatalf("replacement Install() error = %v", err)
	}
	assertDNSConfigFile(t, path, "address=/#/192.168.50.1")

	if err := config.Remove(); err != nil {
		t.Fatalf("Remove() error = %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("configuration still exists after Remove(): %v", err)
	}
	if err := config.Remove(); err != nil {
		t.Fatalf("second Remove() error = %v", err)
	}
}

func TestDNSConfigFileInvalidInstallLeavesExistingFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "onboardd.conf")
	config, err := NewDNSConfigFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("existing\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := config.Install(netip.IPv6Loopback()); err == nil {
		t.Fatal("Install() unexpectedly accepted IPv6")
	}
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(contents) != "existing\n" {
		t.Fatalf("existing configuration changed to %q", contents)
	}
}

func assertDNSConfigFile(t *testing.T, path, addressLine string) {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(contents), addressLine+"\n") {
		t.Fatalf("configuration = %q, want %q", contents, addressLine)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != 0o644 {
		t.Fatalf("configuration mode = %o, want 644", got)
	}
}
