package captive

import (
	"errors"
	"fmt"
	"net/netip"
	"os"
	"path/filepath"
)

const dnsmasqHeader = "# Generated by onboardd. Do not edit.\n"

// DNSConfigurer prepares and removes the wildcard DNS policy used while the
// provisioning access point is active.
type DNSConfigurer interface {
	Install(netip.Addr) error
	Remove() error
}

// DNSConfigFile manages NetworkManager's dnsmasq-shared configuration fragment.
// The caller must install it before activating the provisioning profile so the
// per-connection dnsmasq process reads it at startup.
type DNSConfigFile struct {
	path string
}

// NewDNSConfigFile validates the exact fragment path that DNSConfigFile may change.
func NewDNSConfigFile(path string) (*DNSConfigFile, error) {
	if path == "" {
		return nil, errors.New("DNS configuration path is required")
	}
	if !filepath.IsAbs(path) {
		return nil, errors.New("DNS configuration path must be absolute")
	}
	if filepath.Base(path) == "." || filepath.Base(path) == string(filepath.Separator) {
		return nil, errors.New("DNS configuration path must name a file")
	}
	return &DNSConfigFile{path: filepath.Clean(path)}, nil
}

// renderDNSMasqConfig returns a closed wildcard DNS policy. local=/#/ prevents
// dnsmasq 2.86 and newer from forwarding non-A queries that address=/#/... cannot
// answer locally.
func renderDNSMasqConfig(address netip.Addr) (string, error) {
	if !address.IsValid() || !address.Is4() || address.IsUnspecified() || address.IsMulticast() {
		return "", errors.New("captive DNS address must be a usable IPv4 address")
	}
	return fmt.Sprintf(
		"%saddress=/#/%s\nlocal=/#/\nlocal-ttl=0\n",
		dnsmasqHeader,
		address,
	), nil
}

// Install atomically creates or replaces the configured fragment.
func (config *DNSConfigFile) Install(address netip.Addr) error {
	contents, err := renderDNSMasqConfig(address)
	if err != nil {
		return err
	}

	directory := filepath.Dir(config.path)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create captive DNS configuration directory: %w", err)
	}
	temporary, err := os.CreateTemp(directory, ".onboardd-dnsmasq-*")
	if err != nil {
		return fmt.Errorf("create temporary captive DNS configuration: %w", err)
	}
	temporaryPath := temporary.Name()
	committed := false
	defer func() {
		_ = temporary.Close()
		if !committed {
			_ = os.Remove(temporaryPath)
		}
	}()

	if err := temporary.Chmod(0o644); err != nil {
		return fmt.Errorf("set captive DNS configuration permissions: %w", err)
	}
	if _, err := temporary.WriteString(contents); err != nil {
		return fmt.Errorf("write captive DNS configuration: %w", err)
	}
	if err := temporary.Sync(); err != nil {
		return fmt.Errorf("sync captive DNS configuration: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close captive DNS configuration: %w", err)
	}
	if err := os.Rename(temporaryPath, config.path); err != nil {
		return fmt.Errorf("install captive DNS configuration: %w", err)
	}
	committed = true
	return nil
}

// Remove deletes only the configured onboardd fragment and is safe to call repeatedly.
func (config *DNSConfigFile) Remove() error {
	if err := os.Remove(config.path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("remove captive DNS configuration: %w", err)
	}
	return nil
}
