package captive

import (
	"context"
	"net/netip"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
	"time"
)

func TestProvisionerCanStartAgainAfterStop(t *testing.T) {
	calls := []string{}
	provisioner, err := NewProvisioner(
		&fakeNetworkManager{calls: &calls},
		&fakeDNSConfigurer{calls: &calls},
	)
	if err != nil {
		t.Fatal(err)
	}

	for range 2 {
		session, startErr := provisioner.Start(context.Background(), validProvisioningOptions())
		if startErr != nil {
			t.Fatalf("Start() error = %v", startErr)
		}
		if got := session.activation.UUID; got != "provisioning-uuid" {
			t.Fatalf("session activation UUID = %q", got)
		}
		stopContext, cancel := context.WithTimeout(context.Background(), time.Second)
		stopErr := session.Stop(stopContext)
		cancel()
		if stopErr != nil {
			t.Fatalf("Stop() error = %v", stopErr)
		}
	}

	wantCycle := []string{
		"dns-install:10.42.0.1",
		"start-ap",
		"wait",
		"status",
		"finalize",
		"delete:provisioning-uuid",
		"dns-remove",
	}
	want := append(append([]string{}, wantCycle...), wantCycle...)
	if !reflect.DeepEqual(calls, want) {
		t.Fatalf("calls = %#v, want %#v", calls, want)
	}
}

func TestProvisioningSessionRetriesOnlyFailedResources(t *testing.T) {
	calls := []string{}
	network := &fakeNetworkManager{calls: &calls, deleteFailures: 1}
	dns := &fakeDNSConfigurer{calls: &calls}
	provisioner, err := NewProvisioner(network, dns)
	if err != nil {
		t.Fatal(err)
	}
	session, err := provisioner.Start(context.Background(), validProvisioningOptions())
	if err != nil {
		t.Fatal(err)
	}
	if err := session.Stop(context.Background()); err == nil {
		t.Fatal("first Stop() error = nil")
	}
	if err := session.Stop(context.Background()); err != nil {
		t.Fatalf("second Stop() error = %v", err)
	}
	if got := countCalls(calls, "delete:provisioning-uuid"); got != 2 {
		t.Fatalf("profile delete calls = %d, want 2; calls = %#v", got, calls)
	}
	if got := countCalls(calls, "dns-remove"); got != 1 {
		t.Fatalf("DNS remove calls = %d, want 1; calls = %#v", got, calls)
	}
}

func TestProvisionerReturnsIncompleteFailedStartForCleanupRetry(t *testing.T) {
	calls := []string{}
	network := &fakeNetworkManager{
		calls:          &calls,
		fail:           "wait",
		deleteFailures: 1,
	}
	dns := &fakeDNSConfigurer{calls: &calls}
	provisioner, err := NewProvisioner(network, dns)
	if err != nil {
		t.Fatal(err)
	}
	session, err := provisioner.Start(context.Background(), validProvisioningOptions())
	if err == nil {
		t.Fatal("Start() error = nil")
	}
	if session == nil {
		t.Fatal("Start() discarded the incompletely cleaned session")
	}
	if err := session.Stop(context.Background()); err != nil {
		t.Fatalf("retry Stop() error = %v", err)
	}
	if got := countCalls(calls, "delete:provisioning-uuid"); got != 2 {
		t.Fatalf("profile delete calls = %d, want 2; calls = %#v", got, calls)
	}
	if got := countCalls(calls, "dns-remove"); got != 1 {
		t.Fatalf("DNS remove calls = %d, want 1; calls = %#v", got, calls)
	}
}

func TestProvisionerValidatesDependencies(t *testing.T) {
	calls := []string{}
	if _, err := NewProvisioner(nil, &fakeDNSConfigurer{calls: &calls}); err == nil {
		t.Fatal("nil NetworkManager client unexpectedly accepted")
	}
	if _, err := NewProvisioner(&fakeNetworkManager{calls: &calls}, nil); err == nil {
		t.Fatal("nil DNS configurer unexpectedly accepted")
	}
}

func validProvisioningOptions() ProvisioningOptions {
	return ProvisioningOptions{
		Interface: "wlan0",
		SSID:      "Onboardd Setup",
		Password:  "test-password",
		Address:   netip.MustParsePrefix("10.42.0.1/24"),
		Band:      "bg",
		Wait:      30 * time.Second,
	}
}

func TestRenderDNSMasqConfig(t *testing.T) {
	got, err := renderDNSMasqConfig(netip.MustParseAddr("10.42.0.1"))
	if err != nil {
		t.Fatalf("renderDNSMasqConfig() error = %v", err)
	}
	want := "# Generated by onboardd. Do not edit.\n" +
		"address=/#/10.42.0.1\n" +
		"local=/#/\n" +
		"local-ttl=0\n"
	if got != want {
		t.Fatalf("renderDNSMasqConfig() = %q, want %q", got, want)
	}
}

func TestRenderDNSMasqConfigRejectsUnusableAddresses(t *testing.T) {
	for _, address := range []netip.Addr{
		{},
		netip.IPv6Unspecified(),
		netip.IPv4Unspecified(),
		netip.MustParseAddr("224.0.0.1"),
	} {
		t.Run(address.String(), func(t *testing.T) {
			if _, err := renderDNSMasqConfig(address); err == nil {
				t.Fatalf("renderDNSMasqConfig(%s) unexpectedly succeeded", address)
			}
		})
	}
}

func TestNewDNSConfigFileValidatesPath(t *testing.T) {
	for _, path := range []string{"", "onboardd.conf", "."} {
		t.Run(path, func(t *testing.T) {
			if _, err := NewDNSConfigFile(path); err == nil {
				t.Fatalf("NewDNSConfigFile(%q) unexpectedly succeeded", path)
			}
		})
	}
}

func TestDNSConfigFileInstallReplaceAndRemove(t *testing.T) {
	path := filepath.Join(t.TempDir(), "NetworkManager", "dnsmasq-shared.d", "onboardd.conf")
	config, err := NewDNSConfigFile(path)
	if err != nil {
		t.Fatal(err)
	}

	if err := config.Install(netip.MustParseAddr("10.42.0.1")); err != nil {
		t.Fatalf("Install() error = %v", err)
	}
	assertDNSConfigFile(t, path, "address=/#/10.42.0.1")

	if err := config.Install(netip.MustParseAddr("192.168.50.1")); err != nil {
		t.Fatalf("replacement Install() error = %v", err)
	}
	assertDNSConfigFile(t, path, "address=/#/192.168.50.1")

	if err := config.Remove(); err != nil {
		t.Fatalf("Remove() error = %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("configuration still exists after Remove(): %v", err)
	}
	if err := config.Remove(); err != nil {
		t.Fatalf("second Remove() error = %v", err)
	}
}

func TestDNSConfigFileInvalidInstallLeavesExistingFile(t *testing.T) {
	path := filepath.Join(t.TempDir(), "onboardd.conf")
	config, err := NewDNSConfigFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte("existing\n"), 0o644); err != nil {
		t.Fatal(err)
	}

	if err := config.Install(netip.IPv6Loopback()); err == nil {
		t.Fatal("Install() unexpectedly accepted IPv6")
	}
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(contents) != "existing\n" {
		t.Fatalf("existing configuration changed to %q", contents)
	}
}

func assertDNSConfigFile(t *testing.T, path, addressLine string) {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(contents), addressLine+"\n") {
		t.Fatalf("configuration = %q, want %q", contents, addressLine)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if got := info.Mode().Perm(); got != 0o644 {
		t.Fatalf("configuration mode = %o, want 644", got)
	}
}
